### ISSUE TITLE
Crash when displacing stone in the Displacer with a Complex Moment

### ISSUE THREAD

**Issue by Fortanono** [ZenDarva/Parachronography#5]
I had just upgraded it twice. Crash report: https://pastebin.com/7NaHNawp

**Comment by Fortanono** [comment]
Experimenting with it a bit more: 

- I think it's just that the upgraded ones don't work, apparently. Tried the 8 oak wood process on a Tier 1 and Tier 2 Displacer and the latter crashed and the former did not.
- Also seems to be world-corrupting on one occasion but the world does sometimes load afterwards. Don't have a crash report for that yet, but only 2 oak logs out of 8 became stone.

**Comment by Fortanono** [comment]
UPDATE: This Github seems to be unused. Will look a bit further.

**Comment by ZenDarva** [comment]
The github is used, I just, apparently, don't get notifications for it. Heh.  Looking into this now.

**Comment by ZenDarva** [comment]
I believe 1.6.3 fixes this crash.  If I haven't heard back in a few days, I'm going to close this.

**Comment by ZenDarva** [comment]
I believe 1.6.3 fixes this crash.  If I haven't heard back in a few days, I'm going to close this.
